name: videotrimmer
base: core22
adopt-info: videotrimmer
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
    
slots:
  videotrimmer:
    interface: dbus
    bus: session
    name: org.gnome.gitlab.YaLTeR.VideoTrimmer
  
apps:
  videotrimmer:
    command: usr/bin/video-trimmer
    extensions: [gnome]
    plugs:
      - home
      - audio-playback
      - network
      - optical-drive
      - removable-media
    common-id: org.gnome.gitlab.YaLTeR.VideoTrimmer
    desktop: usr/share/applications/org.gnome.gitlab.YaLTeR.VideoTrimmer.desktop.in
    
parts:  
  videotrimmer:
    source: https://gitlab.gnome.org/YaLTeR/video-trimmer.git
    source-tag: v0.8.1 
    plugin: meson
    parse-info: [usr/share/metainfo/org.gnome.gitlab.YaLTeR.VideoTrimmer.metainfo.xml.in]
    meson-parameters:
      - -Dprefix=/usr
    build-packages:
      - cargo
      - build-essential
      - python3-gi 
      - gobject-introspection 
      - gir1.2-gtk-4.0
      - libadwaita-1-dev
      - libadwaita
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
